<link rel="SHORTCUT ICON" href="./images/phplist.ico" />
<link rel="stylesheet" href="styles/phplist.css" type="text/css" />
</head>

<body class="fixed">

<div id="container">

<div id="header" >
<div id="rack-functions">
<h1 id="logo"><a href="http://www.phplist.com" title="phpList Hosted">phpList</a></h1>
</div>
</div>
<div id="wrapper">		
<div id="mainContent">

<div class="panel">
<div class="content">
