
</div>
</td><td>
<table>
<tr>
<td>
<div class="menutableright">
<?php
  print contextMenu();
  ?>
</div>
<div class="menutableright">
<?php

  print recentlyVisited();
?>


</div>

</td>
</tr>

<tr><td colspan="4">&nbsp;</td></tr>
<tr><td colspan="4">&nbsp;</td></tr>
</table>
<!--TOP TABLE ends-->

</td></tr>


<tr>
<td bgcolor="#ff9900" colspan="3"><img height="1" alt="" src="ui/orange/images/transparent.png" width="1" border="0" /></td>
</tr>

<tr>
<td bgcolor="#ff9900" class="bottom"><img height="1" alt="" src="ui/orange/images/transparent.png" width="1" border="0" /></td>
<td bgcolor="#ff9900" class="bottom">&copy; <a href="http://tincan.co.uk" target="_tincan" class="urhere">tincan limited</a> | <span class="urhere"><?php echo NAME?> powered by </span><a class="urhere" href="http://www.phplist.com" target="_blank">phplist</a> - version <?php echo VERSION?></td>
<td bgcolor="#ff9900" class="bottom"><img height="1" alt="" src="ui/orange/images/transparent.png" width="1" border="0" /></td>
</tr>

<tr>
<td bgcolor="#ff9900" colspan="3"><img height="1" alt="" src="ui/orange/images/transparent.png" width="1" border="0" /></td>
</tr>

<tr>
<td colspan="3"><img height="3" alt="" src="ui/orange/images/transparent.png" width="1" border="0" /></td>
</tr>

<tr>
<td colspan="3" class="bottomrow">
&nbsp;
</td>
</tr>
</tbody>
</table>

</div>
</body></html>
