    </div> <!-- end #content -->

    <div id="right-bar">
        <div id="context-menu">
            <h3>Navigation</h3>
            <?php print contextMenu(); ?>
        </div>
	    <div id="language">
            <?php print $languageswitcher; ?>
        </div>
	</div><!-- end #right-bar -->
	

</div> <!-- end #container -->

<div id="footer">
    <div class="container">
            <a target="_blank" href="http://phplist.com">&copy; phpList ltd.</a> - v<?php echo VERSION?>
        <div class="right">
            <a target="_blank" href="http://resources.phplist.com">Resources</a>&nbsp; 
    </div>
</div>

</body>
</html>

