<link rel="icon" href="./images/phplist.ico" type="image/x-icon">
<link rel="apple-touch-icon" href="./images/phplist-touch-icon.png">
<link rel="apple-touch-icon-precomposed" href="./images/phplist-touch-icon.png">
</head>
<body>
<div id="dialog"></div>
<div id="hiddendiv"></div>

<div id="navigation">
    <div id="main-menu">
        <?php print topMenu(); ?>
    </div>
    <div class="clear"></div>
    <div id="content">
        <!-- content start here -->
