#!/bin/bash

[ -d public_html ] || {
  echo Run from root as ./scripts/cs-fixer
  exit;
}

for file in $(find public_html -name *php | grep -v "admin/help" | grep -v "admin/info" | grep -v "admin/ui" | grep -v "admin/locale" | grep -v "PHPMailer"); do
   echo $file
   php-cs-fixer fix $file
done
